# including default.yaml
defaults:
  - default
  - _self_

agent_workflow: "tool"
agent_func_path: null
default_agent:
  eos_token: "<|im_end|>"

# chat_template: "Answer the given question. You must conduct reasoning inside <think> and </think> first every time you get new information. After reasoning, if you find you lack some knowledge, you can call a search engine inside <tool_call> and </tool_call>, it will return the top searched results between <tool_response> and </tool_response>. You can search as many times as your want. If you find no further external knowledge needed, you can directly provide the answer inside <answer> and </answer>, without detailed illustrations. For example, <answer> Beijing </answer>. Question: {question}"
chat_template: "Answer the given math problem. You must conduct reasoning inside <think> and </think> first every time you get new information or need to solve a subproblem. After reasoning, if you find that a calculation or code is needed, you can use the code interpreter inside <tool_call> and </tool_call>; it will return the result between <tool_response> and </tool_response>. You can run as many code cells as needed. If you find no further computation is necessary, put your final answer within \\boxed{{}}. Question: {question}"

tools_config:
  max_turns: 2
  num_workers: 128
  enable_metrics: True
  enable_rate_limiting: True
  tools:
    python:
      type: sandbox_fusion
      enable_rate_limiting: True
      rate_limit: 30
      timeout: 30
      base_url: "http://127.0.0.1:8080/run_code"
      schema_path: "examples/schema/code.json"
